root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main cmd/main.go"
exclude_dir = ["docker", "docs", "tmp"]
include_ext = ["go"]
exclude_regex = ["_test.go"]
send_interrupt = true
kill_delay = "5000ms"
