version: '3'

tasks:

  install-deps:
    desc: installs development dependencies
    cmds:
      - go install github.com/air-verse/air@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@lates
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  dev:
    deps: [install-deps]
    desc: starts server in development mode.
    dir: '{{.USER_WORKING_DIR}}'
    cmd: air

  build:
    desc: build server in production mode.
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - go build -o build/main cmd/main.go
      - ./build/main

  build-docker:
    desc: build server in production mode inside docker.
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - docker build -t go-framework .
      - docker run -p 3000:3000 go-framework

  build-docker-compose:
    desc: build server in production mode inside docker with docker compose.
    dir: '{{.USER_WORKING_DIR}}'
    cmd: docker compose up --build

  test:
    desc: run tests
    dir: '{{.USER_WORKING_DIR}}'
    cmd: go test ./... -v --count=1

  coverage:
    desc: run tests with coverage
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
    - go test ./... -coverprofile=coverage.out
    - go tool cover -html=coverage.out

  tidy:
    desc: clean go modules, pre-commit hooks and linting.
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - go get -u ./...
      - go mod tidy
      - pre-commit autoupdate
      - golangci-lint run --config=.golangci.yml ./...
      - govulncheck ./...
